### ISSUE TITLE
Windows can't find jycm_viewer_assets

### ISSUE THREAD

**Issue by jasamej** [eggachecat/jycm#9]
First of all, thanks for the amazing app!

Secondly:
I tried to create an executable of my python script. When I tried to use it, I got the following error:
![image](https://user-images.githubusercontent.com/117090/187944178-fa7c5715-ad98-4131-b5dc-e27acafd5530.png)
What it says basically is Windows can't find jycm\\jycm_viewer_assets 
The script works perfectly, but the .exe is always showing this error and I don't know how to fix it.

Is this an error on my end or a bug? Let me know! Thanks!

**Comment by eggachecat** [comment]
@jasamej Hi I would guess the problem is related to the mechanism of windows how to deal the temp folder?
the relative code is [here](https://github.com/eggachecat/jycm/blob/5b08a0660124e1434b33ff8f04da950ae764c298/jycm/helper.py#L67) 
I think you may copy the output (by writing your own _dump_html_output_ like above) to your folder to solve the problem.

**Comment by eggachecat** [comment]
BTW the "main" function of the cmd line is [here](https://github.com/eggachecat/jycm/blob/5b08a0660124e1434b33ff8f04da950ae764c298/jycm/__main__.py)

may it help the scalability and flexibility for your app!

**Comment by jasamej** [comment]
It seems the issue was caused by an external source (_**pyinstaller**_) not importing your module correctly. Your code was not causing it.

I used **cxfreeze** instead and it worked like a charm. Thanks for your support!
